### ISSUE TITLE
Error: Image not found in Sanity

### ISSUE THREAD

**Issue by zvitez** [abmenzel/medusa-file-sanity#1]
Hi! I'm using the plugin together with the "medusa-plugin-sanity". The medusa-plugin-sanity works fine - products are synced to Sanity - but I'm having issues with images - when I try to upload an image via the medusa admin, I get the following error:

Image not found in Sanity
error:   An error occurred while processing product.updated: TypeError: Cannot read properties of undefined (reading '_id')

Might this have something to do with the version of Sanity? I'm using the latest v3.

I'm using the following medusa versions
"dependencies": {
    "@medusajs/admin": "^6.0.1",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "^1.12.0",
    "cors": "^2.8.5",
    "dotenv": "^16.1.4",
    "express": "^4.17.2",
    "medusa-file-sanity": "^1.0.3",
    "medusa-plugin-sanity": "^1.0.2",
  },
  "devDependencies": {
    "@medusajs/medusa-cli": "^1.3.14",
  },

**Comment by abmenzel** [comment]
I'm having issues with the plugin as well at the moment. After updating to a newer version of Medusa it seems that the fileService is not being recognized.

**Comment by abmenzel** [comment]
@zvitez could you try to install the latest version (1.0.4) `npm i medusa-file-sanity@latest` and see if that resolves your issue?

**Comment by zvitez** [comment]
Oh amazing @abmenzel! Works great. Thanks for that, and for the plugin itself!

**Comment by abmenzel** [comment]
> Oh amazing @abmenzel! Works great. Thanks for that, and for the plugin itself!

Great! Glad it worked out :)
